name: Build and Deploy Code On Time with Azure CLI

on:
  push:
    branches:
      - dev

env:
  AZURE_REGION: '"West US"'  # Cambia a tu región de Azure preferida
  RESOURCE_GROUP: 'github-actions'  # Nombre del grupo de recursos
  WEB_APP_NAME: 'test-cot-web-app'  # Nombre de la Web App
  SERVICE_PLAN: 'test-cot-plan'  # Nombre del Plan de Servicio para App Service
  SOLUTION: 'CooperReplenishmentSystem.sln'
  BUILD_PLATFORM: 'Any CPU'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build_and_deploy:
    runs-on: self-hosted    #windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Login to Azure using Service Principal
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Credenciales SP almacenadas en secretos

    # Step 2: Create Resource Group
    - name: 'Create Resource Group'
      run: |
        az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.AZURE_REGION }}

    # Step 3: Create App Service Plan
    - name: 'Create App Service Plan'
      run: |
        az appservice plan create --name ${{ env.SERVICE_PLAN }} --resource-group ${{ env.RESOURCE_GROUP }} --sku F1

    # Step 4: Create Web App
    - name: 'Create Web App'
      run: |
        az webapp create --name ${{ env.WEB_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --plan ${{ env.SERVICE_PLAN }}
      # --runtime '"DOTNETCORE|6.0"'

    # Step 5: Refresh BD with Code On Time
    - name: Refresh BD with Code On Time
      run: |
        codeontime -refresh C:\actions-runner\_work\COT-deploy-QA\COT-deploy-QA -DbConnection "Data Source=teamqa.database.windows.net;Initial Catalog=teamqa-bd;Persist Security Info=True;User ID=team-qa-admin;Password=4dministrad0r$;" -dbprovider "sqlclient"
      working-directory: 'C:\Program Files (x86)\Code OnTime LLC\Code OnTime Generator' 

    # Step 6: Copy NReco.PdfGenerator.dll to WebSite bin
    - name: Copy Microsoft.SqlServer.Types.dll to WebSite bin
      run: |
        cp "C:\actions-runner\_work\Microsoft.SqlServer.Types.dll" "C:\actions-runner\_work\COT-deploy-QA\COT-deploy-QA\WebSite\bin"

    # Step 7: Publish the website using ASP.NET Compiler
    - name: Publish WebSite
      run: |
        aspnet_compiler.exe -nologo -f -v / -p "C:\actions-runner\_work\COT-deploy-QA\COT-deploy-QA\WebSite" "C:\actions-runner\_work\COT-deploy-QA\a"
      working-directory: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'
      
    - name: Create ZIP file
      shell: powershell
      run: Compress-Archive -Path "C:\actions-runner\_work\COT-deploy-QA\a\*" -DestinationPath "C:\actions-runner\_work\COT-deploy-QA\a\your-published-package.zip"

    # Step 8: Deploy application to Azure Web App using Azure CLI
    - name: 'Deploy to Azure Web App'
      run: |
        az webapp deployment source config-zip --name ${{ env.WEB_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --src "C:\actions-runner\_work\COT-deploy-QA\a\your-published-package.zip"  
# Reemplaza con la ruta correcta
